work_dir: ./work_dir/ntu/xsub/semantic_distance
model_saved_name: ./runs/ntu_cs_semantic_distance
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
#  data_path: ./data/ntu/xsub/train_data_joint.npy
#  label_path: ./data/ntu/xsub/train_label.pkl

  data_path: ./data/ntu_light/xsub/train_data_joint.npy
  label_path: ./data/ntu_light/xsub/train_label.pkl

#  data_path: ./data/ntu_light/xsub/joint_distance/train_data_joint.npy
#  label_path: ./data/ntu_light/xsub/joint_distance/train_label.pkl

  # Westworld
#  data_path: ./data/ntu_light/xsub/train_data_joint.npy
#  label_path: ./data/ntu_light/xsub/train_label.pkl

  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
#  data_path: ./data/ntu/xsub/val_data_joint.npy
#  label_path: ./data/ntu/xsub/val_label.pkl

  data_path: ./data/ntu_light/xsub/val_data_joint.npy
  label_path: ./data/ntu_light/xsub/val_label.pkl

  # Westworld
#  data_path: /data/ntu/xsub/val_data_joint.npy
#  label_path: /data/ntu/xsub/val_label.pkl

# model
model: model.semantic.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [30, 40]

# training
device: [0]
batch_size: 3
test_batch_size: 3
num_epoch: 2
nesterov: True

save_score: True
